language: node_js
sudo: false
node_js:
  - 10

services:
  - docker

before_install:
  - bash script/installMarketWatcher.sh

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
